import React, { useState } from "react";
import { Eye, EyeOff, Loader2, ShieldCheck, ArrowRight, ArrowLeft, KeyRound, UserPlus } from "lucide-react";
import { useStore } from "../lib/store";
import { localResetPassword, isBackendOk } from "../lib/api";
import { Button, Input, Field, Modal, ModalHead, cx } from "../lib/ui";
import { Logo } from "../lib/layout";

type Mode = "login" | "register" | "forgot" | "reset";

function ForgotModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const s = useStore();
  const [email, setEmail] = useState("");
  const [username, setUsername] = useState("");
  const [pw, setPw] = useState("");
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState<{ ok: boolean; msg: string } | null>(null);
  const backend = isBackendOk();

  const submit = async () => {
    setBusy(true);
    setResult(null);
    try {
      if (backend) {
        const r = await s.forgotPassword(email);
        setResult({ ok: true, msg: r.resetToken ? `Reset token generated. Use it below to set a new password: ${r.resetToken}` : r.message });
      } else {
        if (!username.trim() || pw.length < 6) throw new Error("Enter username and a new password (min 6 chars).");
        await localResetPassword(username, pw);
        setResult({ ok: true, msg: "Password updated locally. Sign in with your new password." });
      }
    } catch (e) {
      setResult({ ok: false, msg: e instanceof Error && e.message !== "LOCAL_MODE" ? e.message : "Something went wrong." });
    } finally {
      setBusy(false);
    }
  };

  return (
    <Modal open={open} onClose={onClose} width="max-w-md">
      <ModalHead title="RECOVER ACCESS" sub={backend ? "Email-based recovery via backend" : "Local recovery (no backend connected)"} onClose={onClose} />
      <div className="space-y-4 p-6">
        {backend ? (
          <Field label="Account Email" hint="A reset link/token is generated by the server and emailed if SMTP is configured.">
            <Input value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@company.com" />
          </Field>
        ) : (
          <>
            <Field label="Username"><Input value={username} onChange={(e) => setUsername(e.target.value)} placeholder="admin" /></Field>
            <Field label="New Password" hint="Local mode has no email server — recovery sets a new password directly on this device.">
              <Input type="password" value={pw} onChange={(e) => setPw(e.target.value)} placeholder="Min. 6 characters" autoComplete="new-password" />
            </Field>
          </>
        )}
        {result && (
          <p className={cx("rounded-lg border px-3.5 py-2.5 text-[12px] leading-relaxed", result.ok ? "border-safe/40 bg-safe/10 text-safe" : "border-threat/40 bg-threat/10 text-threat")}>
            {result.msg}
          </p>
        )}
      </div>
      <div className="flex justify-end gap-2.5 border-t border-line px-6 py-4">
        <Button variant="ghost" onClick={onClose}>Cancel</Button>
        <Button variant="primary" disabled={busy} onClick={submit}>
          {busy ? <Loader2 size={13} className="animate-spin" /> : <KeyRound size={13} />} {backend ? "Send Reset" : "Reset Password"}
        </Button>
      </div>
    </Modal>
  );
}

export default function Login({ onBack }: { onBack: () => void }) {
  const s = useStore();
  const [mode, setMode] = useState<Mode>("login");
  const [username, setUsername] = useState("admin");
  const [password, setPassword] = useState("");
  const [reg, setReg] = useState({ name: "", username: "", email: "", password: "" });
  const [show, setShow] = useState(false);
  const [remember, setRemember] = useState(true);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState("");
  const [forgot, setForgot] = useState(false);

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    setErr("");
    if (!username.trim() || !password.trim()) { setErr("Enter both username and password."); return; }
    setBusy(true);
    try {
      await s.login(username, password);
    } catch (ex) {
      setErr(ex instanceof Error ? ex.message : "Sign-in failed.");
    } finally {
      setBusy(false);
    }
  };

  const submitRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    setErr("");
    if (!reg.name.trim() || !reg.username.trim() || !reg.email.includes("@") || reg.password.length < 6) {
      setErr("Fill all fields — password must be at least 6 characters.");
      return;
    }
    setBusy(true);
    try {
      await s.register(reg);
    } catch (ex) {
      setErr(ex instanceof Error ? ex.message : "Registration failed.");
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="relative flex min-h-screen items-center justify-center overflow-hidden bg-abyss px-4 py-10">
      <div className="pointer-events-none absolute inset-0 bg-gridlines opacity-70 [mask-image:radial-gradient(ellipse_75%_65%_at_50%_40%,black,transparent)]" />
      <div className="pointer-events-none absolute left-1/2 top-[-220px] h-[560px] w-[860px] -translate-x-1/2 rounded-full bg-[radial-gradient(closest-side,rgba(34,211,238,0.09),transparent)]" />
      <div className="pointer-events-none absolute bottom-[-260px] right-[-160px] h-[520px] w-[520px] rounded-full bg-[radial-gradient(closest-side,rgba(59,130,246,0.07),transparent)]" />

      <svg className="pointer-events-none absolute inset-0 h-full w-full opacity-[0.07]" aria-hidden>
        <g stroke="#22D3EE" strokeWidth="1" fill="none">
          <path d="M0 140 H260 L320 200 H520" />
          <path d="M1440 520 H1180 L1120 460 H900" />
          <path d="M180 900 V640 L240 580 V380" />
          <path d="M1260 40 V260 L1200 320 V520" />
        </g>
        <g fill="#22D3EE">
          <circle cx="260" cy="140" r="3" /><circle cx="520" cy="200" r="3" />
          <circle cx="1180" cy="520" r="3" /><circle cx="900" cy="460" r="3" />
          <circle cx="180" cy="640" r="3" /><circle cx="1200" cy="320" r="3" />
        </g>
      </svg>

      <div className="anim-fadeup relative w-full max-w-[420px]">
        <button onClick={onBack} className="mb-5 flex items-center gap-1.5 font-mono text-[11px] tracking-wider text-t3 transition-colors hover:text-pri">
          <ArrowLeft size={12} /> BACK TO OVERVIEW
        </button>

        <div className="rounded-[14px] border border-line bg-card p-8 shadow-[0_28px_80px_rgba(0,0,0,0.5)]">
          <div className="mb-7 flex items-center gap-3">
            <Logo size={38} />
            <div className="leading-tight">
              <p className="text-[17px] font-extrabold tracking-tight text-t1">SafeHaven</p>
              <p className="font-mono text-[9px] font-semibold tracking-[0.22em] text-t3">AI SECURITY PLATFORM</p>
            </div>
          </div>

          {mode === "register" ? (
            <>
              <h1 className="text-[22px] font-bold text-t1">Create operator account</h1>
              <p className="mt-1.5 text-[13px] leading-relaxed text-t2">Provision a new console user. Works locally or against the backend.</p>
              <form onSubmit={submitRegister} className="mt-6 space-y-4">
                <Field label="Full Name"><Input value={reg.name} onChange={(e) => setReg({ ...reg, name: e.target.value })} placeholder="e.g. Sarah Mitchell" /></Field>
                <div className="grid grid-cols-2 gap-3">
                  <Field label="Username"><Input value={reg.username} onChange={(e) => setReg({ ...reg, username: e.target.value })} placeholder="s.mitchell" /></Field>
                  <Field label="Password"><Input type="password" value={reg.password} onChange={(e) => setReg({ ...reg, password: e.target.value })} placeholder="Min. 6 chars" autoComplete="new-password" /></Field>
                </div>
                <Field label="Email"><Input value={reg.email} onChange={(e) => setReg({ ...reg, email: e.target.value })} placeholder="s.mitchell@company.com" /></Field>
                {err && <p className="rounded-lg border border-threat/40 bg-threat/10 px-3 py-2 text-[12px] font-medium text-threat">{err}</p>}
                <Button variant="primary" size="lg" className="w-full" type="submit" disabled={busy}>
                  {busy ? <Loader2 size={15} className="animate-spin" /> : <UserPlus size={15} />} CREATE ACCOUNT
                </Button>
              </form>
              <button onClick={() => { setMode("login"); setErr(""); }} className="mt-4 w-full text-center text-[12.5px] font-semibold text-pri transition-colors hover:text-prisoft">
                Already have an account? Sign in
              </button>
            </>
          ) : (
            <>
              <h1 className="text-[22px] font-bold text-t1">Welcome back</h1>
              <p className="mt-1.5 text-[13px] leading-relaxed text-t2">Sign in to your security operations dashboard.</p>
              <form onSubmit={submit} className="mt-6 space-y-4">
                <Field label="Username">
                  <Input value={username} onChange={(e) => setUsername(e.target.value)} placeholder="admin" autoComplete="username" />
                </Field>
                <Field label="Password">
                  <div className="relative">
                    <Input
                      type={show ? "text" : "password"}
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                      placeholder="••••••••"
                      autoComplete="current-password"
                      className="pr-11"
                    />
                    <button type="button" aria-label={show ? "Hide password" : "Show password"} onClick={() => setShow((v) => !v)} className="absolute right-3 top-1/2 -translate-y-1/2 text-t3 transition-colors hover:text-t1">
                      {show ? <EyeOff size={16} /> : <Eye size={16} />}
                    </button>
                  </div>
                </Field>
                <div className="flex items-center justify-between">
                  <label className="flex cursor-pointer items-center gap-2 text-[12.5px] text-t2">
                    <input type="checkbox" checked={remember} onChange={(e) => setRemember(e.target.checked)} className="h-4 w-4 rounded border-edge bg-ink accent-[#22D3EE]" />
                    Remember me
                  </label>
                  <button type="button" onClick={() => setForgot(true)} className="text-[12.5px] font-semibold text-pri transition-colors hover:text-prisoft">
                    Forgot password?
                  </button>
                </div>
                {err && <p className="rounded-lg border border-threat/40 bg-threat/10 px-3 py-2 text-[12px] font-medium text-threat">{err}</p>}
                <Button variant="primary" size="lg" className="w-full" type="submit" disabled={busy}>
                  {busy ? (<><Loader2 size={15} className="animate-spin" /> AUTHENTICATING…</>) : (<>SIGN IN <ArrowRight size={15} /></>)}
                </Button>
              </form>
              <button onClick={() => { setMode("register"); setErr(""); }} className="mt-4 w-full text-center text-[12.5px] font-semibold text-pri transition-colors hover:text-prisoft">
                New here? Create an account
              </button>
            </>
          )}

          <div className="mt-5 rounded-lg border border-line bg-ink px-3.5 py-2.5 text-center font-mono text-[10px] leading-relaxed text-t3">
            DEFAULT: <span className="text-pri">admin</span> / <span className="text-pri">admin123</span>
            <br />BACKEND CONNECTED: <span className={s.backendOk ? "text-safe" : "text-warn"}>{s.backendOk ? "YES — JWT + MONGODB" : "NO — LOCAL MODE"}</span>
          </div>
        </div>

        <p className="mt-5 flex items-center justify-center gap-2 font-mono text-[10.5px] tracking-[0.14em] text-t3">
          <ShieldCheck size={13} className="text-safe" /> PROTECTED BY SAFEHAVEN AI
        </p>
      </div>

      <ForgotModal open={forgot} onClose={() => setForgot(false)} />
    </div>
  );
}
